name: SDL Examples Snapshot Build 2.11

on:
  push:
    branches: 
      - develop
  pull_request:
    branches: 
      - develop

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Cache Maven
      uses: actions/cache@v1.1.2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-maven-
    - name: Build with Maven for Scala 2.11
      run: mvn -B clean test --file pom.xml
